import Link from 'next/link'
import { supabase } from '@/lib/supabase'
import PropertyCard from '@/components/PropertyCard'

export const dynamic = 'force-dynamic'

export default async function Home() {
  const { data: properties } = await supabase.from('properties').select('id, slug, title, status, price, cover_image, property_types(name_ar), cities(name_ar)').eq('is_published', true).order('created_at', { ascending: false }).limit(4)
  return <main className="rafal-page overflow-hidden"><section className="relative isolate border-b border-[#E8E9E9]/10"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_20%,rgba(232,233,233,.16),transparent_28rem),radial-gradient(circle_at_86%_78%,rgba(21,64,45,.95),transparent_28rem)]"/><div className="mx-auto flex min-h-[580px] max-w-7xl items-center px-6 py-20 md:px-10"><div data-aos="fade-up"><p className="mb-5 text-xs font-bold tracking-[.28em] text-[#E8E9E9]/60">RAFAL REAL ESTATE</p><h1 className="max-w-3xl text-5xl font-extrabold leading-[1.15] text-[#E8E9E9] md:text-7xl">رفال العقارية<br/><span className="text-[#E8E9E9]/55">نقودك للمكان المناسب.</span></h1><p className="mt-7 max-w-xl text-lg leading-9 text-[#E8E9E9]/70">من الخبر إلى أنحاء المملكة، نساعدك على العثور على فرصتك العقارية التالية بثقة ووضوح.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/properties" className="rafal-button px-7 py-3.5">استكشف العقارات</Link><Link href="/contact" className="rounded-full border border-[#E8E9E9]/25 px-7 py-3.5 font-bold text-[#E8E9E9] transition hover:bg-[#E8E9E9]/10">تواصل معنا</Link></div></div></div></section><section className="mx-auto max-w-7xl px-6 py-20 md:px-10"><div className="mb-10 flex flex-wrap items-end justify-between gap-4" data-aos="fade-up"><div><p className="text-sm text-[#E8E9E9]/50">أحدث الفرص المتاحة</p><h2 className="mt-2 text-3xl font-extrabold text-[#E8E9E9]">عقارات مميزة لك</h2></div><Link href="/properties" className="text-sm font-bold text-[#E8E9E9] underline decoration-[#E8E9E9]/40 underline-offset-8 hover:decoration-[#E8E9E9]">عرض كل العقارات</Link></div>{properties?.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4" data-aos="fade-up">{properties.map((property) => <PropertyCard key={property.id} property={property}/>)}</div> : <div className="rafal-surface rounded-2xl p-10 text-center text-[#E8E9E9]/65">لا توجد عقارات منشورة حاليًا.</div>}</section></main>
}
